{
 "title": "SX API Gateway",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "title": "Uptime and SLA/SLO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Uptime percentage for the current time range",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(up{job=\"sx\"}[1m])"
    }
   ]
  },
  { "title": "Gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Request rate",
   "type": "timeseries",
   "description": "Rate of requests per second by route",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(sx_route_request_count{job=\"sx\"}[1m])",
     "legendFormat": "{{service}}: {{method}} {{route}} -> {{path}} = {{status}}"
    }
   ]
  },
  {
   "title": "Latency 90th",
   "type": "timeseries",
   "description": "90th percentile of request latency",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (service, route, path, method, status) (histogram_quantile(0.9, rate(sx_route_request_bucket{job=\"sx\"}[5m])))",
     "legendFormat": "{{service}}: {{method}} {{route}} -> {{path}} = {{status}}"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Cache hit rate",
   "type": "stat",
   "description": "Percentage of successful cache lookups. Low cache lookup rates may indicates your cache partitioning is too aggressive.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (service, route, path, method) (avg_over_time(\n  (\n    sx_cache_get_response_hit{job=\"sx\"}\n  /\n    sx_cache_get_response_count{job=\"sx\"}\n  )[$__range:1m]\n))",
     "legendFormat": "{{service}}: {{method}} {{route}} -> {{path}}"
    }
   ]
  },
  {
   "title": "Cache latency 90th",
   "type": "timeseries",
   "description": "90th percentile of cache operations latency",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(sx_cache_get_response_bucket{job=\"sx\"}[5m])))",
     "legendFormat": "get response"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(sx_cache_set_response_bucket{job=\"sx\"}[5m])))",
     "legendFormat": "set response"
    }
   ]
  },
  { "title": "Go runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "Number of running goroutines",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"sx\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "OS Threads",
   "type": "timeseries",
   "description": "Number of running OS threads",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_threads{job=\"sx\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC duration",
   "type": "timeseries",
   "description": "Average Go GC duration",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum{job=\"sx\"}[5m]) / rate(go_gc_duration_seconds_count{job=\"sx\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC CPU overhead",
   "type": "timeseries",
   "description": "Percentage of CPU used by the GC vs the program",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "go_memstats_gc_cpu_fraction", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "In use heap memory",
   "type": "timeseries",
   "description": "Amount of heap memory used.\nNote the system memory used is more: memory can be preallocated by Go but not used yet.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "go_memstats_heap_inuse_bytes", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "In use stack memory",
   "type": "timeseries",
   "description": "Amount of stack memory used.\nNote the system memory used is more: memory can be preallocated by Go but not used yet.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "go_memstats_stack_inuse_bytes", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}