name: CI

on:
  pull_request:
  push:

jobs:
  test:
    name: Unit tests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "^v1.17"

      - name: Test
        run: |
          go test -v -cover -coverprofile=c.out -bench ... -benchmem
          go tool cover -func=c.out

  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        continue-on-error: true

  kind-test:
    name: Kubernetes integration tests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          skipClusterCreation: true

      - name: Build Docker image
        run: ./scripts/build-docker-local.sh

      - name: Run integration tests in Kubernetes
        run: ./scripts/test-kind.sh
